services:
  db:
    restart: always
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=tutordb
      - TZ=Asia/Yekaterinburg
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    restart: always
    build: .
    depends_on:
      - db
    environment:
      - TZ=Asia/Yekaterinburg
